
#spring:
#  data:
#    elasticsearch:
#      ####集群名称
#      cluster-name: myes
#      ####地址
#      cluster-nodes: localhost:9300

spring:
  redis:
    database: 1
    timeout: 6000ms
    host: 47.102.40.227
    port: 6379
    password: redis123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  data:
    elasticsearch:
      ####集群名称
      cluster-name: myes
      ####地址
      cluster-nodes: localhost:9300








